-- ============================================================
-- Waitlist provisioning for the Pro ($250/month) tier
-- ============================================================
-- Purpose:
--   Every visitor who clicks "Join waitlist" on the Pro card
--   submits (planId, email, reward) to POST /api/waitlist,
--   which inserts a row into `waitlist_subscriptions`.
--
--   When an admin marks a row `verified = true`, the backend
--   can grant the Pro tier to that email via the existing
--   entitlement flow. "verified" is the trigger that converts
--   an unlock path (Discord / Skool / newsletter / refer) into
--   a paid billing link that gets emailed to the visitor.
--
--   This file is for you to run against your Supabase project
--   (SQL Editor in the dashboard, or `psql`/`supabase db push`).
--   It is idempotent within a single run: use IF NOT EXISTS so
--   re-running it won't error on an already-created table/index.
-- ============================================================

-- 1) The waitlist subscription table
CREATE TABLE IF NOT EXISTS
  waitlist_subscriptions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         text                NOT NULL,            -- e.g. 'pro'
    email           text                NOT NULL,
    reward          text                NOT NULL,            -- discord | skool | subscribe-newsletter | refer-friend
    verified        boolean             NOT NULL DEFAULT false,
    notes           text                NULL,                -- internal/admin notes
    created_at      timestamptz         NOT NULL DEFAULT now(),
    updated_at      timestamptz         NOT NULL DEFAULT now(),

    -- One active waitlist entry per (plan_id, email, reward).
    -- If a visitor submits the same combo again, treat it as a
    -- no-op / duplicate rather than a second row.
    UNIQUE (plan_id, email, reward)
  );

-- 2) Auto-update `updated_at` on every change
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_waitlist_updated_at ON waitlist_subscriptions;
CREATE TRIGGER trigger_waitlist_updated_at
  BEFORE UPDATE ON waitlist_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- 3) Row-level security
ALTER TABLE waitlist_subscriptions ENABLE ROW LEVEL SECURITY;

-- Public insert: anyone can add themselves to the waitlist.
-- We do NOT expose reads/writes to the public; only the
-- backend (via a service role or a restricted anon key with
-- INSERT-only grant) touches this table at runtime.
CREATE POLICY waitlist_insert_anon
  ON waitlist_subscriptions
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Nobody else can read or write from the client side.
CREATE POLICY waitlist_no_read_anon
  ON waitlist_subscriptions
  FOR SELECT
  TO anon
  USING (false);

CREATE POLICY waitlist_no_update_anon
  ON waitlist_subscriptions
  FOR UPDATE
  TO anon
  USING (false);

-- Optional: if you have a separate "admin" role / JWT claim,
-- uncomment and tune so your own dashboard can verify rows.
-- CREATE POLICY waitlist_manage_admin
--   ON waitlist_subscriptions
--   FOR ALL
--   TO authenticated
--   USING (auth.jwt()->>'role' = 'admin');
--   WITH CHECK (auth.jwt()->>'role' = 'admin');

-- 4) Useful indexes (only matter once you have real volume)
CREATE INDEX IF NOT EXISTS
  waitlist_subscriptions_email_idx
  ON waitlist_subscriptions (email);

CREATE INDEX IF NOT EXISTS
  waitlist_subscriptions_verified_idx
  ON waitlist_subscriptions (verified)
  WHERE verified = false;  -- unverified rows only
